# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 878a850900b0c53ee50f92d62d80da018457e5966079177097ef42f2530cc5a5966a0f56e9e5e7c9837b38852f66013224a146d12b35c79db43f082acc2c0370

test:
  secret_key_base: 59b0f8be897ec34ffac482c45508b086c808e47fe183751939b7dc4d0756ed920f59bdebc298018da24edf60ae58f716686ee60dc85ac9dfcffb12b232f63af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
